config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "photos#index"
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
	#Mount paperclip image
	has_attached_file :image

	 #This validates the type of file uploaded. According to this, only images are allowed.
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

   #Validates file, file type and file size
  validates_attachment :image, presence: true,
  content_type: { content_type: "image/jpeg" },
  size: { in: 0..10.megabytes }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

 #Index action, photos gets listed in the order at which they were created
 def index
  @photos = Photo.order('created_at')
 end

 #New action for creating a new photo
 def new
  @photo = Photo.new
 end

 #Create action ensures that submitted photo gets created if it meets the requirements
 def create
  @photo = Photo.new(photo_params)
  if @photo.save
   flash[:notice] = "Successfully added new photo!"
   redirect_to root_path
  else
   flash[:alert] = "Error adding new photo!"
   render :new
  end
 end

   #Destroy action for deleting an already uploaded image
  def destroy
  @photo = Photo.find(params[:id])
    if @photo.destroy
      flash[:notice] = "Successfully deleted photo!"
      redirect_to root_path
    else
      flash[:alert] = "Error deleting photo!"
    end
  end

 private

 #Permitted parameters when creating a photo. This is used for security reasons.
 def photo_params
  params.require(:photo).permit(:title, :image)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
	<ul class="nav">
		<li><%= link_to 'Home', root_path %></li>
		<li><%= link_to 'Upload New Image', new_photo_path %></li>
	</ul>
	<div class="navbar-brand">
		<h1>SneakPic</h1>
	</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SneakPeek</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Renders navigation file located at app/views/layouts/_navigation.html.erb -->
    <%= render "layouts/navigation" %>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>
    <div class="container-fluid">
      <%= yield %>
    </div>

    <footer>
      <p>App Courtesy of Zeshan Munir</p>
    </footer>
  </body>
</html>

app/views/photos/index.html.erb
<div class="page-header"><h1>Your Sneakers</h1></div>

<div class="media">
  <% @photos.each do |photo| %>
    <div class="media-pic">
      <!-- Renders image -->
      <%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %><br>

      <%# link_to 'Remove', photo_path(photo), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
    </div>
    <div class="media-body">
      <h4 class="media-heading"><%= photo.title %></h4>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<div class="page-header">
  <h1>Upload Photo</h1>
</div>

<div class="form ">
  <%= form_for @photo, html: { multipart: true } do |f| %>
    <% if @photo.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:" %>
        </h2>
        <ul>
          <% @photo.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
            <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <%= text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>

    <div class="form-group">
          <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
      </div>
  <% end %>

</div>